### PR TITLE
Described Rmd headers with links to examples

### PR DESCRIPTION
**Pull request by lmmx**
I worked out how to turn the knit button into a sort of 'make' for Rmarkdown documents (render multiple source files for inclusion into a single document), thought it might belong here? Also linked to Karl Broman's Tools4RR course and a lecture specifically on knitting :memo:

### CODE REVIEW

**Comment by iamciera** [comment]
Thanks @lmmx .  If you want to add yourself as a contributor, go ahead and add yourself here: [https://github.com/ropensci/reproducibility-guide/blob/gh-pages/contributors/index.md](https://github.com/ropensci/reproducibility-guide/blob/gh-pages/contributors/index.md)

**Comment by lmmx** [comment]
Ah cool, will do :smile: Also could you tell me the standard way to boot up the jekyll engine ? First time using it, I ran `jekyll build` from the top level and it changed a bunch of files I hadn't edited, and prefixed some links to `/assets/...` as `/reproducibility-guide/assets/...` so I had to look at the diff and do it manually. Do you have to point it to another folder?

**Comment by jhollist** [comment]
@lmmx This is from memory so I may be a bit off.  But...

use `jekyll serve` instead.  That will allow you to preview the file at 127.0.0.1:4000 (I think thats the port).  If you add `_site` to `.gitignore` then you can commit and push without the other rendered files.  Github will take care of the build of the site as gh-pages are rendered with jekyll.

@iamciera might correct me if the reproducibility guide uses something other than straight up jekyll.

**Comment by iamciera** [comment]
I always use (in the root folder)

`jekyll serve --watch baseurl = ""` 

This builds it and serves it in your browser like @jhollist was explaining. That should serve it up at http://localhost:4000/ .  The `--watch` re-builds every time you save any file in the folder, so you never have to re-serve it while your working, just refresh the page.

**Comment by iamciera** [comment]
No matter what jekyll is a pain point.  I wish there was a easier system for this type of collaborative project on Github, but I have yet to find anything. @jhollist talk with people at the Ropensci unconference about other (easier) systems. Jealous - I can't go.  When the twitter-verse is blowing up during the unconference I am going to have serious FOMO.

**Comment by jhollist** [comment]
@iamciera, I agree it is a bit of a pain and wish I could talk with folks.  I won't be there, but will be following along remotely when I can.  

I wonder if working up a CONTRIBUTING.md with some suggestions on how best to contribute would be helpful?  I don't have time in the next couple of weeks, but could probably carve some out later in March to pull a first draft together.

**Comment by cboettig** [comment]
@lmmx Looks very nice. Not entirely sure I follow though -- is this saying that I can add a field called `knit` to the yaml header that defines a custom function, and that function is automatically used by the `knitr` button in RStudio?

**Comment by lmmx** [comment]
Yup, sounds like you've followed fine :smiley:  I saw it referred to as a 'hook' in [this thread](https://github.com/rstudio/rmarkdown/issues/277#issuecomment-59060741). I've described the whole thing in a bit more detail [in a blog post here](http://biochemistri.es/one-weird-rmd-trick).

Like you say, the function defined at this field is called where `rmarkdown::render` would be usually upon clicking Knit, allowing a custom function to receive its 2 parameters: the input file and encoding.

If another header field hasn't already done so, the `knit:` field will remove the drop-down options on the Knit button for Knit HTML, Knit PDF, etc.

I'm currently looking at prefixing that call to `rmarkdown::render` with a call to `brew` ([as done here](http://stackoverflow.com/a/23458768/2668831)), which'd allow for inclusion of files (`includes: after_body: [...]`) by `list.files(pattern = ...)` globbing rather than an explicit list, thus make it easier to scale projects up using this setup in a repo.

I don't know about you but when I've used `knitcitations` for anything over a handful of citations I've had to wait around for the metadata to re-download even though I only added a couple in one section since last knitting. A modular setup like this can avoid that, since you can choose to knit individual sections (Rmd ⇒ md) and just include them (then optionally convert the composite md ⇒ PDF/HTML _etc._ if markdown isn't the desired end format).

I've got [a working example as a repo on GitHub](https://github.com/lmmx/tomasetti-vogelstein-2015) now if you want to try it out: 
- open 'documents/Analysis.Rmd' in the RStudio editor and ensure `setwd('documents')`
- click the Knit button ⇒
  - all component .Rmd files convert to .md,
  - these are appended to the converted 'Analysis.Rmd' and written to 'README.md' in the top level,
  - 'README.md' is converted to 'Tomasetti and Vogelstein analysis post.html' (the only part that explicitly states output format rather than relying on YAML headers) in the documents sub-directory,
  - lastly this HTML is displayed (because it's the first call to `render` without `quiet=TRUE` and apparently the "Output created" message is what triggers RStudio's previewer).

**Comment by cboettig** [comment]
@lmmx That is awesome; what a gem of an undocumented feature!  Thanks for the additional links; I think this PR could make it a bit more obvious how this works (as the blog post does).  

Um, is there a way to call said custom function from the command-line? (other than using the function definition itself?).  Ideally it would be nice to tell readers/users that they can either press the button in rstudio, or call function `x` on the command-line and expect the same result (without the latter option involving copy-pasting some potentially long/un-intuitive string).

**Comment by lmmx** [comment]
On a related note, comment within an issue just opened re: the above: “[_There are really powerful tools to create documents with r and markdown but imho they lack simple examples to help users get started._](https://github.com/lmmx/devnotes/issues/1#issuecomment-76837337)”

Calling said custom function... would require just stealing it out of the YAML I guess (I can't see an easy way to do this in the rmarkdown package, but a simple file reading can extract it)

``` r
customKnit <- function(filename) {
    my.rmd <-  paste( readLines(filename) , sep = "\n" )
    yaml.range <- which('---' == my.rmd)[1:2]
    yaml.header.range <- setdiff(do.call(seq, as.list(yaml.range)), yaml.range)
    my.yaml <- paste(my.rmd[yaml.header.range], collapse="\n")
    knit.function <- as.function(as.list(yaml::yaml.load(my.yaml)$knit))()
    evaluated <- eval(parse(text = call(knit.function())))
    return(evaluated(filename, "UTF-8"))
}
customKnit('analysis.Rmd')
```

> To return just the function, instead use `return(evaluated)`

<pre>processing file: ./analysis-i.md
processing file: ./analysis-ii.md
processing file: ./analysis-iii.md
/usr/lib/rstudio/bin/pandoc/pandoc README.utf8.md --to html --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash-implicit_figures --output './Tomasetti and Vogelstein analysis post.html' --smart --email-obfuscation none --self-contained --standalone --section-divs --template /home/louis/R/x86_64-pc-linux-gnu-library/3.1/rmarkdown/rmd/h/default.html --variable 'theme:bootstrap' --include-in-header /tmp/RtmpxcVxJL/rmarkdown-str297b58d05edd.html --mathjax --variable 'mathjax-url:https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML' --no-highlight --variable highlightjs=/home/louis/R/x86_64-pc-linux-gnu-library/3.1/rmarkdown/rmd/h/highlight 
Output created: ./Tomasetti and Vogelstein analysis post.html</pre>

I can't see a way of doing this as is, and suppose if RStudio/knitr users would want to have this as a command-line option the above would have to be a feature added in the rmarkdown package.

**Edit** - the above plus checking for a package function, reverting to `rmarkdown::render` if no `knit:` hook is found:

``` r
custom_knit <- function(filename, encoding = "UTF-8") {
    rmd.content <-  paste( readLines(filename) , sep = "\n" )
    # reads file as character vector split on newlines
    yaml.range <- which('---' == rmd.content)[1:2]
    if (all(is.na(yaml.range))) { knit.function <- rmarkdown::render } else {
      yaml.header.range <- setdiff(do.call(seq, as.list(yaml.range)), yaml.range)
      rmd.yaml <- paste(rmd.content[yaml.header.range], collapse="\n")
      knit.hook <- yaml::yaml.load(rmd.yaml)$knit
      if (!is.null(knit.hook)) { 
        knit.func.str <- as.function(as.list(knit.hook))()
        knit.function <- eval(parse(text = call(knit.func.str)))
      } else knit.function <- rmarkdown::render
    }
    return(knit.function(filename, encoding))
}
```

**Comment by cboettig** [comment]
right ... Or just defining the function in a package I guess.  Anyway,
probably not a big issue.  Very cool that this works!

**Comment by earcanal** [comment]
Any idea why this

    knit: (function(inputFile, encoding) { bookdown::render_book(inputFile, encoding=encoding, output_dir='docs')})

fails with

    Error in basename(input) : object 'inputFile' not found
    Calls: <Anonymous> -> <Anonymous> -> <Anonymous> -> basename
    Execution halted

**Pull request merged**
